### ISSUE TITLE
Failing to build tl

### ISSUE THREAD

**Issue by dataO1** [nagy/nur-packages#1]
I found your  NUR derivation for tl, the teal compiler, I hope it's fine if i file an issue here, i don't know how to do this else with NUR packages.

When trying to build, i get the following error: 
```
Error: Build error: Failed installing tl.lua in /nix/store/7h16wy9wqqlir3s7yz81cpnlx2c2d2ch-lua5.3-tl-0.13.2-1/tl-0.13.2-1-rocks/tl/0.13.2-1/lua/tl.lua: The source and destination are the same files
```

I couldn't find any information about it on the internet, do you happen to know, what may be wrong? I suppose it has something to do with luarock?

**Comment by nagy** [comment]
I could reproduce this and have pushed a fix for this by switching to the latest commit of `tl` for the time being. See the commit message for a reference to the upstream issue. Feel free to reopen if it still does not work.

**Comment by dataO1** [comment]
Great, that worked, thanks!
